### ISSUE TITLE
Merge Request - Hinweis bei fehlendem Assignee

### ISSUE THREAD

**Issue by renao** [renao/prosoz-dashboard#24]
Wird via Jira ein MR erstellt, so gibt es keinen ausgewählten Assignee (oder er wird auch von Hand mal vergessen).

Generell sollten MRs auffallen, für die niemand zuständig ist ... und für den Style sollte ggf. auch irgendwie ein Fallback-Image o.ä. genutzt werden - aktuell stirbt es einfach nur nicht ;-)

**Comment by forbon** [comment]
Das Problem sollte mit den Änderungen aus #33 behoben sein.
